// Спайк S6 — Firebird вместо PostgreSQL.
//
// Проверяются четыре вещи, и они выбраны не произвольно: на каждой из них
// конструкция может сломаться так, что заметить это можно будет только под
// нагрузкой.
//
//   1. Драйвер работает на Java 8. Версия JDK у нас не обсуждается: это
//      последний JDK с CORBA в составе (ADR-0004).
//
//   2. POST_EVENT доходит до клиента в контейнерной сети. Это тот же риск,
//      на котором споткнулась CORBA: сервер устанавливает ОБРАТНОЕ
//      соединение к клиенту, и адрес, по которому он его видит, может
//      оказаться недостижимым.
//
//   3. Событие приходит ПОСЛЕ фиксации, а не в момент выполнения. Иначе
//      конвейер outbox прочитал бы строку, которой ещё нет.
//
//   4. SKIP LOCKED действительно пропускает занятые строки. Без этого
//      два потребителя либо блокируют друг друга, либо обрабатывают одну
//      строку дважды.

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

import org.firebirdsql.event.EventManager;
import org.firebirdsql.event.FBEventManager;

public final class FirebirdProbe {

    static int testNo = 0;
    static int failures = 0;

    static void ok(String name) {
        System.out.println("ok " + (++testNo) + " - " + name);
    }

    static void notOk(String name) {
        System.out.println("not ok " + (++testNo) + " - " + name);
        failures++;
    }

    static void check(String name, boolean cond) {
        if (cond) ok(name); else notOk(name);
    }

    static void diag(String s) {
        System.out.println("# " + s);
    }

    static String host = System.getenv().getOrDefault("FB_HOST", "db");
    static int port = Integer.parseInt(System.getenv().getOrDefault("FB_PORT", "3050"));
    static String dbPath = System.getenv().getOrDefault("FB_DB", "/var/lib/firebird/data/sonder.fdb");
    static String user = System.getenv().getOrDefault("FB_USER", "sysdba");
    static String pass = System.getenv().getOrDefault("FB_PASSWORD", "masterkey");

    static String url() {
        return "jdbc:firebirdsql://" + host + ":" + port + "/" + dbPath + "?charSet=UTF-8";
    }

    static Connection open() throws SQLException {
        Connection c = DriverManager.getConnection(url(), user, pass);
        c.setAutoCommit(false);
        return c;
    }

    static void exec(Connection c, String sql) throws SQLException {
        try (Statement st = c.createStatement()) {
            st.execute(sql);
        }
    }

    static void execQuiet(Connection c, String sql) {
        try {
            exec(c, sql);
        } catch (SQLException ignored) {
            // Объекта могло не быть: подготовка схемы идемпотентна.
        }
    }

    public static void main(String[] args) throws Exception {
        final int planned = 11;
        System.out.println("1.." + planned);
        diag("spike S6 - Firebird как замена PostgreSQL");
        diag("url: " + url());

        // --- 1. Драйвер и соединение --------------------------------------
        Connection conn = null;
        long deadline = System.currentTimeMillis() + 90_000L;
        Exception last = null;
        while (System.currentTimeMillis() < deadline) {
            try {
                conn = open();
                break;
            } catch (SQLException e) {
                last = e;
                Thread.sleep(1000);
            }
        }
        if (conn == null) {
            notOk("соединение с Firebird за 90 с: " +
                  (last == null ? "?" : last.getMessage()));
            System.out.println("# ИТОГ: база не поднялась");
            System.exit(1);
        }
        ok("драйвер Jaybird работает на Java " +
           System.getProperty("java.specification.version"));

        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(
                 "select rdb$get_context('SYSTEM','ENGINE_VERSION') from rdb$database")) {
            rs.next();
            diag("версия движка: " + rs.getString(1));
        }
        conn.commit();

        // --- 2. Схема ------------------------------------------------------
        execQuiet(conn, "drop trigger outbox_notify");
        execQuiet(conn, "drop table outbox");
        conn.commit();

        exec(conn,
            "create table outbox (" +
            "  id bigint generated by default as identity primary key," +
            "  aggregate_id varchar(40) not null," +
            "  event_type varchar(60) not null," +
            "  payload varchar(400) not null," +
            "  status varchar(10) default 'PENDING' not null," +
            "  attempts integer default 0 not null)");
        conn.commit();

        // POST_EVENT — аналог NOTIFY. Событие ставится в очередь транзакции
        // и рассылается движком только при её фиксации.
        exec(conn,
            "create trigger outbox_notify for outbox after insert as " +
            "begin post_event 'outbox_new'; end");
        conn.commit();
        ok("схема и триггер с POST_EVENT созданы");

        // --- 3. События в контейнерной сети --------------------------------
        //
        // Здесь тот же риск, что и у CORBA: сервер устанавливает обратное
        // соединение к клиенту. Если он видит клиента по недостижимому
        // адресу, события просто не придут — молча.
        final AtomicInteger eventCount = new AtomicInteger();
        final AtomicLong firstEventAt = new AtomicLong();
        final CountDownLatch gotEvent = new CountDownLatch(1);

        EventManager em = new FBEventManager();
        // Имена setHost/setPort — из Jaybird 4. В пятой версии их
        // переименовали в setServerName/setPortNumber, но пятая требует
        // более новой Java, а у нас она зафиксирована ADR-0004.
        em.setHost(host);
        em.setPort(port);
        em.setUser(user);
        em.setPassword(pass);
        em.setDatabase(dbPath);

        boolean eventsUp = false;
        try {
            em.connect();
            em.addEventListener("outbox_new", event -> {
                eventCount.addAndGet(event.getEventCount());
                firstEventAt.compareAndSet(0, System.nanoTime());
                gotEvent.countDown();
            });
            eventsUp = true;
            ok("подписка на событие установлена");
        } catch (Exception e) {
            notOk("подписка на событие не установилась: " + e.getMessage());
            diag("это ровно тот риск, ради которого спайк и делался");
        }

        // --- 4. Событие приходит только после фиксации ---------------------
        if (eventsUp) {
            try (PreparedStatement ps = conn.prepareStatement(
                     "insert into outbox (aggregate_id, event_type, payload) " +
                     "values (?, ?, ?)")) {
                ps.setString(1, "u-andrey");
                ps.setString(2, "post.created");
                ps.setString(3, "тело с кириллицей");
                ps.executeUpdate();
            }

            // До фиксации события быть не должно.
            boolean early = gotEvent.await(1500, TimeUnit.MILLISECONDS);
            check("до фиксации событие не приходит", !early);

            long t0 = System.nanoTime();
            conn.commit();

            boolean arrived = gotEvent.await(10, TimeUnit.SECONDS);
            if (arrived) {
                long ms = (firstEventAt.get() - t0) / 1_000_000L;
                ok("событие дошло до клиента в контейнерной сети");
                diag("задержка доставки события: " + ms + " мс");
            } else {
                notOk("событие не дошло за 10 с");
                diag("сервер устанавливает обратное соединение к клиенту — "
                     + "тот же класс проблемы, что IOR у CORBA");
            }
        } else {
            notOk("проверка отложенной доставки пропущена");
            notOk("проверка доставки события пропущена");
        }

        // --- 5. Кириллица через драйвер ------------------------------------
        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(
                 "select payload from outbox rows 1")) {
            rs.next();
            String got = rs.getString(1);
            check("кириллица переживает круг через базу",
                  "тело с кириллицей".equals(got));
            if (!"тело с кириллицей".equals(got)) {
                diag("получено: " + got);
            }
        }
        conn.commit();

        // --- 6. SKIP LOCKED ------------------------------------------------
        //
        // Два потребителя дренируют очередь одновременно. Без SKIP LOCKED
        // они либо встают друг за другом, либо берут одну строку дважды.
        try (Statement st = conn.createStatement()) {
            st.execute("delete from outbox");
        }
        conn.commit();

        try (PreparedStatement ps = conn.prepareStatement(
                 "insert into outbox (aggregate_id, event_type, payload) " +
                 "values (?, ?, ?)")) {
            for (int i = 0; i < 40; i++) {
                ps.setString(1, "agg-" + i);
                ps.setString(2, "e.type");
                ps.setString(3, "p" + i);
                ps.addBatch();
            }
            ps.executeBatch();
        }
        conn.commit();

        String drainSql =
            "select id from outbox where status = 'PENDING' " +
            "order by id rows 10 with lock skip locked";

        boolean skipLockedWorks;
        try (Connection probe = open();
             Statement st = probe.createStatement();
             ResultSet rs = st.executeQuery(drainSql)) {
            int n = 0;
            while (rs.next()) n++;
            skipLockedWorks = n > 0;
            probe.rollback();
            check("синтаксис WITH LOCK SKIP LOCKED поддерживается", skipLockedWorks);
            diag("выбрано строк за раз: " + n);
        } catch (SQLException e) {
            skipLockedWorks = false;
            notOk("WITH LOCK SKIP LOCKED не поддерживается: " + e.getMessage());
        }

        if (skipLockedWorks) {
            final List<Long> takenA = new ArrayList<>();
            final List<Long> takenB = new ArrayList<>();

            try (Connection ca = open(); Connection cb = open()) {
                // A берёт первые десять и держит их.
                try (Statement sa = ca.createStatement();
                     ResultSet ra = sa.executeQuery(drainSql)) {
                    while (ra.next()) takenA.add(ra.getLong(1));
                }
                // B в это же время обязан получить ДРУГИЕ строки, а не ждать.
                long t0 = System.currentTimeMillis();
                try (Statement sb = cb.createStatement();
                     ResultSet rb = sb.executeQuery(drainSql)) {
                    while (rb.next()) takenB.add(rb.getLong(1));
                }
                long waited = System.currentTimeMillis() - t0;

                diag("A взял " + takenA.size() + ", B взял " + takenB.size()
                     + ", B ждал " + waited + " мс");

                check("второй потребитель не заблокирован", waited < 3000);
                check("оба получили работу",
                      !takenA.isEmpty() && !takenB.isEmpty());

                List<Long> overlap = new ArrayList<>(takenA);
                overlap.retainAll(takenB);
                check("одна строка не досталась двоим", overlap.isEmpty());
                if (!overlap.isEmpty()) {
                    diag("пересечение: " + overlap);
                }

                ca.rollback();
                cb.rollback();
            }
        } else {
            notOk("проверка конкурентного дренажа пропущена");
            notOk("проверка распределения работы пропущена");
            notOk("проверка отсутствия пересечения пропущена");
        }

        // --- 7. Откат не должен рассылать событие --------------------------
        if (eventsUp) {
            int before = eventCount.get();
            try (PreparedStatement ps = conn.prepareStatement(
                     "insert into outbox (aggregate_id, event_type, payload) " +
                     "values (?, ?, ?)")) {
                ps.setString(1, "rolled");
                ps.setString(2, "e.rollback");
                ps.setString(3, "x");
                ps.executeUpdate();
            }
            conn.rollback();
            Thread.sleep(1500);
            check("откат не рассылает событие", eventCount.get() == before);
        } else {
            notOk("проверка отката пропущена");
        }

        if (eventsUp) {
            try { em.disconnect(); } catch (Exception ignored) { }
        }
        conn.close();

        // Расхождение с планом опаснее провала: оно означает, что часть
        // проверок не выполнилась, а мы этого не заметили.
        if (testNo != planned) {
            System.out.println("# ВНИМАНИЕ: выполнено " + testNo +
                               " проверок из " + planned);
            failures++;
        }

        if (failures == 0) {
            System.out.println("# ИТОГ: спайк S6 пройден");
        } else {
            System.out.println("# ИТОГ: провалов " + failures);
        }
        System.exit(failures == 0 ? 0 : 1);
    }
}
